export const FETCH_INFO_REQUEST = 'FETCH_INFO_REQUEST';
export const FETCH_INFO_SUCCESS = 'FETCH_INFO_SUCCESS';
export const FETCH_INFO_FAILURE = 'FETCH_INFO_FAILURE';

export const FETCH_RELATED_REQUEST = 'FETCH_RELATED_REQUEST';
export const FETCH_RELATED_SUCCESS = 'FETCH_RELATED_SUCCESS';
export const FETCH_RELATED_FAILURE = 'FETCH_RELATED_FAILURE';

export const RESTORE_STORE = 'RESTORE_STORE';